apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  destination:
    server: "https://kubernetes.default.svc"
  source:
    path: manifest
    repoURL: "https://github.com/vickydevopsorg/argocd"
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true